### ISSUE TITLE
vague error message

### ISSUE THREAD

**Issue by magichowl** [tumashu/bbdb-android#1]
When I use
```elisp
M-x bbdb-android-import RET
```
the error message on "*Messages" buffer is as follows.

```
(Shell command succeeded with no output)
2432 KB/s (6385664 bytes in 2.564s)
cl--position: Wrong type argument: listp, "NAME"   
```

Where NAME is a person's name.
I tried to get rid of error from the side of android's contact by removing duplicated names.
Some times it worked, but not always, even if there is only one contact called "NAME".

Therefore, I think there are some conditions that bbdb can't accept a contact. If you know the detail, it would be more friendly the error emit the reason why bbdb reject a contact.

**Comment by tumashu** [comment]
to little info, i suggest you send me a sample contacts2.db

**Comment by magichowl** [comment]
I've been deleting contacts whole night, while I can't find any hint
for the error. The error may still occur when a contact only contains
two fields (name, phone number).

**Comment by magichowl** [comment]
Sorry for sending you a large db file, as I have no app at hand to handle it.

after I tried to import, the error is 

(Shell command succeeded with no output)
3450 KB/s (7966720 bytes in 2.254s)
Wrote /home/pan/.emacs.d/bbdb-vcard/media/image-a26d27ce30dd1c09bdc36484303c0bf14ae93208.jpg
cl--position: Wrong type argument: listp, "孟倩"

That indicates the contact with name "孟倩" may be invalid for bbdb.

**Comment by tumashu** [comment]
In my opinion, you should check bbdb-vcard's version you installed, because bbdb-android need 
a bbdb-vcard function,   you should install bbdb-vcard from melpa or 
   https://github.com/tohojo/bbdb-vcard

**Comment by tumashu** [comment]
The contact2.db you sent me, can import mostly, only some duplicate contacts which can't deal with,
you should edit from android phone.

**Comment by tumashu** [comment]
```
Wrote /home/feng/.emacs.d/bbdb-vcard/media/image-a26d27ce30dd1c09bdc36484303c0bf14ae93208.jpg
if: Mail address "yzz****n@****.edu.cn" is used by "詹**"

```

The above problem is that you store  email "yz***n@***"  in two names in android phone,
when bbdb merge contact, it will check name and email,  if a email with two name
,it will think this is a problem.

**Comment by magichowl** [comment]
I find that if a contact contain the field relating qq contact, it is also a problem.

**Comment by magichowl** [comment]
A contact named  "王志*"　has only one field, i.e. phone number, I don't know why it goes wrong.

**Comment by magichowl** [comment]
I keep deleting contacts one by one. 
It would be better run without break (outputting all illegal contacts at one time), instead of break on a fail.

**Comment by magichowl** [comment]
The number of contacts has shrink to 118 compared to 500+ yesterday. 
Sadly, the error keep popping, and the illegal contacts reported and deleted seems not follow some orders (alphabetic of pinyin). 

Now I doubt what you said   
```
The contact2.db you sent me, can import mostly...
```

I can send you the db file of 118 contacts.

**Comment by tumashu** [comment]
what wrong with qq?  error？or not imported?

If not imported, it is because that bbdb-vcard can't deal with QQ

**Comment by tumashu** [comment]
```
I can send you the db file of 118 contacts.
```
ok, i will try it again

**Comment by magichowl** [comment]
When a contact has the binding with qq, bbdb-android-import will result the same error.

After split the contact into two contacts (e.g. sharing the same name, one with a phone number, another with only qq info), the error will be gone once I delete the contact with qq info.

**Comment by magichowl** [comment]
Why the db file today is still of size 8M compare to yesterday. Is it because I haven't converting all contacts to db file? That is to say, the error occurs when converting to db,

and the function
```
bbdb-android-import-contacts-db
```
haven't been called? 

I think that make sense that

```
The contact2.db you sent me, can import mostly...
```

**Comment by tumashu** [comment]
for your contact2.db, I can import 119 contacts and no problem....

**Comment by tumashu** [comment]
```
(bbdb-android-import-contacts-db "~/Downloads/android-contacts-20150705.db")
```

**Comment by tumashu** [comment]
一个可能的问题是：contacts2.db 不兼容。。。。，相同的 sqlite 命令，解析出的结果不一致。。。。

**Comment by tumashu** [comment]
我给你发了一份我转换得到的bbdb内容，你可以看看。。。。

**Comment by magichowl** [comment]
> 你怎么安装的，确定加载的是最新的bbdb-vcard? 是不是你搜索目录中有旧版本或者其
> 编译文件？
>
用　emacs 自带的　package-install 安装的　bbdb-vcard

package-list-packages 里面没有　obsolete 文件

el-get-list-pakcages 里也没有

> (locate-library "bbdb-vcard.el") 结果是什么？

"/home/pan/.emacs.d/elpa/bbdb-vcard-20150611.2336/bbdb-vcard.el"

用了你转换的bbdb后export 到手机上没有问题，接着import到电脑上出错了：

```
Do you want to import from android phone? (y or n) y
(Shell command succeeded with no output)
1853 KB/s (602112 bytes in 0.317s)
cl--position: Wrong type argument: listp, "齐佩*"
```

太神奇了

**Comment by magichowl** [comment]
BTW, I installed sqlite3_3.8.7.4-1_amd64.deb on Ubuntu 15.04

**Comment by tumashu** [comment]
你再检查一下那个 贾惠* 看看联系人信息中是不是出现了非法字符，比如 ;

**Comment by tumashu** [comment]
终于发现了原因，这是 bbdb-vcard 的一个bug，不过也是我引入的 ：-），因为我导入联系人的时候，
一直不区分姓和名，所以我的配置中添加了一行：
```
(setq bbdb-vcard-name-imported-priority 
       '(formated-name first-last  bbdb-vcard-generate-bbdb-name))
```

这个bug在处理姓和名分开的情况下才会出现，所以我一直没有发现，我已经给 bbdb-vcard 提交了补丁，估计很快就会修复， 所以我的建议有两个：

1. 等待修复
2. 不区分姓和名

另外也可以参考我的bbdb配置：

https://github.com/tumashu/emacs-helper/blob/master/eh-bbdb3.el

最后要感谢同学。。。。。

**Comment by magichowl** [comment]
good stuff, so is bbdb-china, my contacts were a mess. 😓 

I use mu4e by default, so it's inspiring to have these. 

Nice meeting you.

**Comment by tumashu** [comment]
i want to know the status of importing 500+ contacts :-)

**Comment by magichowl** [comment]
How sick u r.😊


1. The attempt of importing original 599 contacts fails as one contact's
nickname is another contact's name.
```
bbdb-record-set-field: Alternate name address "孙*/M" is used by "孙*/M"
```

the error msg is precise.

2. The 2ed try for the version of 280 contacts fails as one mail
address is shared by two contacts,

```
bbdb-record-set-field: Mail address "yzz***@*.**.cn" is used by "詹**"
```

3. some of 239 contacts failed with unclear reason.

Finally, I **figured out** that #.bbdb# file may be created even if not all
contacts are imported. Therefore, some errors below occurs

```
bbdb-record-set-field: Mail address "j*ai.d*g@gmail.com" is used by "J*i D*g(imported-2408)"
```

```
bbdb-record-set-field: Mail address "b*e.r*e@gmail.com" is used by "B*e Ro*e"
```

After I delete temp file #.bbdb# file and close the corresponding
buffer, the errors disappear.

**Comment by tumashu** [comment]
多谢反馈，你应该检查名字包含imported的联系人，这些联系人应该手动合并到其他联系人，请了解bbdb合并联系人的相关操作

**Comment by magichowl** [comment]
Thx for the tip.

**Comment by tumashu** [comment]
我提交了一个bbdb-vcard补丁，用来处理你上述提到的一些问题，我用我的android手机测试了一下，暂时没有发现什么问题，等合并后，同学帮测试一下吧，毕竟你的联系人很多，也许能测试出潜在的问题。

另外建议用git等版本管理软件管理你的bbdb库，绝对好用。。。

这是pull-requist: https://github.com/tohojo/bbdb-vcard/pull/10

**Comment by magichowl** [comment]
好的

我没想到要用git，我试试看，不过，原始版本合不进现在的精简版了，差异显示
是一块巨大的hunk.

我之前删了好多联系人，记在文本里

ABC 125456
Bob 6543589
Clair 4543803

如果有一个新的特性能批量创建联系人，那会很方便。

**Comment by tumashu** [comment]
git 作为一个定期备份工具也是值得的。。。而且当导入新的联系人的时候，可以用diff check

```
我之前删了好多联系人，记在文本里 
ABC 125456 
Bob 6543589 
Clair 4543803
```

这个bbdb有专门的工具： bbdb-snarf.el

**Comment by tumashu** [comment]
另外我推荐的包是: bbdb-handy, 当然这个包也是我维护滴，它的github页面有一个简单的视频，看看就知道是干什么了。。

**Comment by magichowl** [comment]
买一赠一呀，　哈哈　能从拼音首字母快速选邮件地址　这个功能貌似不错
